name: My First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
       - name: Print Greeting
         run: echo "Hellow World"
       - name: Print GoodBye
         run: echo "Done Bye!"
